name: t

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps:
      - name: Debugging with t
        uses: mxschmitt/action-tmate@v3.9
        timeout-minutes: 360
        with:
          limit-access-to-actor: true
